using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xunit;

namespace CodingRules;

public sealed class InlineConditionClassificationTests
{
    [Theory]
    [InlineData("(a > 0 && b > 0) || ready", "CR0200")]
    [InlineData("a > 0 && b > 0 && ready", "CR0201")]
    [InlineData("a > 0 || b > 0", "CR0202")]
    [InlineData("int.Parse(text) > 0", "CR0203")]
    [InlineData("text.StartsWith(\"a\") || text.StartsWith(\"b\") || text.StartsWith(\"c\")", "CR0204")]
    [InlineData("!text.EndsWith(\"a\") && !text.EndsWith(\"b\") && !text.EndsWith(\"c\")", "CR0204")]
    [InlineData("(int.Parse(text) > 0 && ready) || b > 0", "CR0200")]
    public async Task EachReasonHasBothTerminatingFixes(string expression, string id)
    {
        var document = InlineConditionTestFixture.Document("class C { void M(int a, int b, bool ready, string text) { if (" + expression + ") { } } }");
        Assert.Equal(id, Assert.Single(await InlineConditionTestFixture.Diagnostics(document)).Id);
        foreach (var key in new[] { InlineConditionCodeFixProvider.ExtractKey, InlineConditionCodeFixProvider.ExpandKey })
        {
            var changed = await InlineConditionTestFixture.Fix(document, key);
            await InlineConditionTestFixture.Compiles(changed);
            Assert.Empty(await InlineConditionTestFixture.Diagnostics(changed));
        }
    }

    [Theory]
    [InlineData("x >= 0 && x <= 100")]
    [InlineData("0 <= x && 100 >= x")]
    [InlineData("x < 0 || x >= 100")]
    [InlineData("!double.IsFinite(x) || x <= 0")]
    [InlineData("double.IsNaN(x) || x < 0")]
    [InlineData("text is not null && text.Length > 0")]
    [InlineData("text is null || !System.IO.File.Exists(text)")]
    [InlineData("text!.StartsWith(\"a\") || text.StartsWith(\"b\")")]
    [InlineData("Unknown(x) && Unknown(x)")]
    [InlineData("a > b && b > a")]
    [InlineData("x is < 0 or > 1")]
    [InlineData("ready & ready & ready")]
    [InlineData("ready | ready | ready")]
    [InlineData("ready ^ ready ^ ready")]
    public async Task ConservativeInvariantAndUnknownNegatives(string expression)
    {
        var source = "class C { bool Unknown(double x) => true; void M(double x, double a, double b, bool ready, string? text) { if (" + expression + ") { } } }";
        Assert.Empty(await InlineConditionTestFixture.Diagnostics(InlineConditionTestFixture.Document(source)));
    }

    [Theory]
    [InlineData("(int.Parse(text) > 0 && ready) || b > 0", "CR0200", "CR0203")]
    [InlineData("text.StartsWith(\"a\") || text.StartsWith(\"b\") || text.StartsWith(\"c\")", "CR0204", "CR0201")]
    public async Task DisablingHigherReasonExposesEnabledLowerReason(string expression, string disabled, string expected)
    {
        var source = "class C { void M(bool ready, int b, string text) { if (" + expression + ") { } } }";
        var config = "root = true\n[*]\ndotnet_diagnostic." + disabled + ".severity = none\n";
        var diagnostics = await InlineConditionTestFixture.Diagnostics(InlineConditionTestFixture.Document(source, config));
        Assert.Equal(expected, Assert.Single(diagnostics).Id);
        config += string.Join("\n", new[] { "CR0200", "CR0201", "CR0202", "CR0203", "CR0204" }
            .Select(id => "dotnet_diagnostic." + id + ".severity = none"));
        Assert.Empty(await InlineConditionTestFixture.Diagnostics(InlineConditionTestFixture.Document(source, config)));
    }

    public static IEnumerable<object[]> UnsafeRoots()
    {
        yield return new object[] { "using System; using System.Linq.Expressions; class C { static bool A()=>true; static bool Use(bool x)=>x; Expression<Func<bool>> e = () => Use(A() && A() && A()); }" };
        yield return new object[] { "using System; using System.Linq.Expressions; class C { static bool A()=>true; Expression<Func<bool>> e = () => A() && A() && A(); }" };
        yield return new object[] { "class C { void M(bool a, bool b, bool c) { if (a /* preserve */ && b && c) { } } }" };
        yield return new object[] { "class C { void M(bool a, bool b, bool c) { goto end; if (a && b && c) { } end: ; } }" };
        yield return new object[] { "class C { static bool Use(bool condition, [System.Runtime.CompilerServices.CallerArgumentExpression(\"condition\")] string text = \"\") => condition; bool M(bool a, bool b, bool c) => Use(a && b && c); }" };
        yield return new object[] { "class C { bool A([System.Runtime.CompilerServices.CallerLineNumber] int line = 0) => true; bool M() => A() && A() && A(); }" };
        yield return new object[] { "class C { void M(string text, bool a) { if (a && int.TryParse(text, out var n) && n > 0) { } System.Console.WriteLine(n); } }" };
        yield return new object[] { "// <auto-generated/>\nclass C { void M(bool a, bool b, bool c) { if (a && b && c) { } } }" };
    }

    [Theory]
    [MemberData(nameof(UnsafeRoots))]
    public async Task UnsafeIndividualCasesHaveNoDiagnostic(string source)
    {
        Assert.Empty(await InlineConditionTestFixture.Diagnostics(InlineConditionTestFixture.Document(source)));
    }

    [Theory]
    [InlineData("int.TryParse(text, out var n) && n > 0", "System.Console.WriteLine(n);", "System.Console.WriteLine(n);")]
    [InlineData("!int.TryParse(text, out var n) || n <= 0", "return;", "System.Console.WriteLine(n);")]
    public async Task OutDeclarationKeepsBodyAndLaterScope(string condition, string body, string later)
    {
        var document = InlineConditionTestFixture.Document("class C { void M(string text) { if (" + condition + ") { " + body + " } " + later + " } }");
        var diagnostic = Assert.Single(await InlineConditionTestFixture.Diagnostics(document));
        Assert.Equal("CR0203", diagnostic.Id);
        var action = Assert.Single(await InlineConditionTestFixture.Actions(document, diagnostic));
        Assert.Equal(InlineConditionCodeFixProvider.ExpandKey, action.EquivalenceKey);
        var changed = await InlineConditionTestFixture.Fix(document, InlineConditionCodeFixProvider.ExpandKey);
        await InlineConditionTestFixture.Compiles(changed);
        Assert.Empty(await InlineConditionTestFixture.Diagnostics(changed));
    }
}
