using System.Threading.Tasks;
using Xunit;

namespace CodingRules;

public sealed class NamedArgumentHostTests
{
    [Theory]
    [InlineData("class C { static void M(int x,int y) {} static void F() { M(1,2); } }", "M(x: 1,y: 2)")]
    [InlineData("class C { void M(int x,int y) {} static void F(C? c) { c?.M(1,2); } }", "M(x: 1,y: 2)")]
    [InlineData("class C { static int F() { int M(int x,int y) => x; return M(1,2); } }", "M(x: 1,y: 2)")]
    [InlineData("delegate int D(int x,int y); class C { static int F(D d) => d(1,2); }", "d(x: 1,y: 2)")]
    [InlineData("class C { public C(int x,int y) {} static C F() => new C(1,2); }", "new C(x: 1,y: 2)")]
    [InlineData("class C { public C(int x,int y) {} public required int P { get; init; } static C F() => new(1,2) { P = 3 }; }", "new(x: 1,y: 2)")]
    [InlineData("class B { public B(int x,int y) {} } class C : B { public C() : base(1,2) {} }", "base(x: 1,y: 2)")]
    [InlineData("class C { public C(int x,int y) {} public C() : this(1,2) {} }", "this(x: 1,y: 2)")]
    [InlineData("class B { public B(int x,int y) {} } class C() : B(1,2);", "B(x: 1,y: 2)")]
    [InlineData("class A : System.Attribute { public A(int x,int y) {} public int P { get; set; } } [A(1,2,P=3)] class C {}", "A(x: 1,y: 2,P=3)")]
    [InlineData("class A : System.Attribute { public A(System.Type x,System.Type y) {} } [A(typeof(int),typeof(string))] class C {}", "A(x: typeof(int),y: typeof(string))")]
    [InlineData("enum E { A,B } class A : System.Attribute { public A(E[] x,E[] y) {} } [A(new[]{E.A},new[]{E.B})] class C {}", "A(x: new[]{E.A},y: new[]{E.B})")]
    [InlineData("static class E { public static int M(this int x,int y) => x; } class C { static int F() => E.M(1,2); }", "E.M(x: 1,y: 2)")]
    [InlineData("static class E { public static int M(this string s,int x,int y) => x; } class C { static int F() => \"a\".M(1,2); }", "M(x: 1,y: 2)")]
    [InlineData("interface I { void M(int source,int target); } class C { static void F(I c) { c.M(1,2); } }", "M(source: 1,target: 2)")]
    [InlineData("class C { static void M<T>(T x,T y) {} static void F() { M(new { P=1 },new { P=2 }); } }", "M(x: new { P=1 },y: new { P=2 })")]
    [InlineData("class C { static void M(ref int x,out int y) { y=x; } static int F() { int v=1; M(ref v,out var b); return b; } }", "M(x: ref v,y: out var b)")]
    public async Task AcceptedHostsHaveSavedActions(string source, string expected)
    {
        var document = NamedArgumentTestFixture.Document(source);
        await StatementOperationTestFixture.Compiles(document);
        var diagnostic = Assert.Single(await NamedArgumentTestFixture.Diagnostics(document));
        var changed = await NamedArgumentTestFixture.Fix(document, diagnostic);
        Assert.Contains(expected, (await changed.GetTextAsync()).ToString());
        Assert.Empty(await NamedArgumentTestFixture.Diagnostics(changed));
    }

    [Theory]
    [InlineData("class C { public int this[int x,int y] => x; static int F(C c) => c[1,2]; }")]
    [InlineData("class A : System.Attribute { public A(int x) {} public int P { get; set; } } [A(1,P=2)] class C {}")]
    [InlineData("class C { static int M(int x,int y) => x; static System.Linq.Expressions.Expression<System.Func<int>> F() => () => M(1,2); }")]
    [InlineData("// <auto-generated/>\nclass C { static void M(int x,int y) {} static void F() => M(1,2); }")]
    [InlineData("class C { static void F(dynamic d) => d.M(1,2); }")]
    public async Task ExcludedHosts(string source) => Assert.Empty(await NamedArgumentTestFixture.Diagnostics(NamedArgumentTestFixture.Document(source)));
}
