<Project Sdk="Anton.SourceGeneration.Sdk/1.0.0">
  <PropertyGroup>
    <PackageId>Anton.CodingRules</PackageId>
    <Version>0.1.0</Version>
    <Description>C# coding rules with Roslyn diagnostics and code fixes.</Description>
    <Authors>Anton C.</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/AntonC9018/CodingRules</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
